In [1]:
import nomination_crawler

In [2]:
nomination_crawler.crawl_nomination_speech(save=True, './Nomination_speech.csv')

100%|██████████| 86/86 [01:39<00:00,  1.15s/it]

,name,date,speech
0,Joseph R. Biden,"August 20, 2020","[Good evening., Ella Baker, a giant of the civ..."
1,Hillary Clinton,"July 28, 2016","[Thank you all very, very much! Thank you for ..."
2,Barack Obama,"September 06, 2012",[The First Lady. Thank you so much. Tonight I ...
3,Barack Obama,"August 28, 2008",[To Chairman Dean and my great friend Dick Dur...
4,John F. Kerry,"July 29, 2004","[I'm John Kerry and I'm reporting for duty., W..."
...,...,...,...
80,Ulysses S. Grant,"June 10, 1872","[To Thomas Settle et al., Washington D. C, Jun..."
81,Ulysses S. Grant,"May 29, 1868","[GENERAL JOSEPH R. HAWLEY,PRESIDENT NATIONAL U..."
82,Ulysses S. Grant,"May 29, 1868",[Mr. President and Gentlemen of the National U...
83,Abraham Lincoln,"June 27, 1864","[EXECUTIVE MANSION, WASHINGTON, June 27, 1864...."
84,Abraham Lincoln,"May 19, 1860","[Mr. Chairman and gentlemen of the committee, ..."

In [4]:
# import pandas as pd
# df = pd.read_csv('./Nomination_speech.csv')

In [10]:
# for idx, data in enumerate(df.values):
#     lname = data[1].split(' ')[-1]
#     year = data[2].split(' ')[-1]
#     print(lname, year)

Biden 2020
Clinton 2016
Obama 2012
Obama 2008
Kerry 2004
Jr. 2000
Clinton 1996
Clinton 1992
Dukakis 1988
Mondale 1984
Carter 1980
Carter 1976
McGovern 1972
Humphrey 1968
Johnson 1964
Kennedy 1960
Stevenson 1956
Stevenson 1952
Truman 1948
Roosevelt 1944
Roosevelt 1940
Roosevelt 1936
Roosevelt 1932
Smith 1928
Davis 1924
Cox 1920
Cox 1920
Wilson 1916
Bryan 1896
Bryan 1896
Cleveland 1892
Cleveland 1892
Cleveland 1888
Cleveland 1888
Cleveland 1884
Cleveland 1884
Polk 1844
Buren 1835
Trump 2020
Trump 2016
Romney 2012
McCain 2008
Bush 2004
Bush 2000
Dole 1996
Bush 1992
Bush 1988
Reagan 1984
Reagan 1980
Ford 1976
Nixon 1972
Nixon 1968
Goldwater 1964
Nixon 1960
Eisenhower 1956
Eisenhower 1952
Dewey 1948
Dewey 1944
Willkie 1940
Landon 1936
Landon 1936
Hoover 1932
Hoover 1932
Hoover 1928
Hoover 1928
Coolidge 1924
Harding 1920
Hughes 1916
Taft 1912
Taft 1908
Roosevelt 1904
McKinley 1900
McKinley 1896
McKinley 1896
Harrison 1892
Harrison 1888
 1888
Blane 1884
Blane 1884
Garfield 1880
Grant 1872
Grant 1868
Grant 1868
Lincoln 1864
Lincoln 1860